# Generated by Django 3.2 on 2021-05-01 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210501_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('created_by', models.CharField(max_length=250, verbose_name='Created By')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expires_at', models.DateField(verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('subcategory', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.subcategory')),
            ],
        ),
    ]
