# Generated by Django 3.2 on 2021-05-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.CharField(max_length=250, null=True, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz', to='quiz.subcategory', verbose_name='SubCategory'),
        ),
    ]
