# Generated by Django 3.2 on 2021-04-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_for_exam',
            field=models.BooleanField(default=False, verbose_name='Is For Exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Multiple Choice'), (1, 'True/False')], default=0, verbose_name='Question Type'),
        ),
    ]
