# Generated by Django 3.2 on 2021-05-01 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz'),
        ('question', '0002_auto_20210501_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.quiz', verbose_name='Quiz'),
        ),
    ]
