# Generated by Django 3.2 on 2021-05-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210504_2326'),
        ('question', '0007_alter_question_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(null=True, to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subcategories',
            field=models.ManyToManyField(to='quiz.SubCategory'),
        ),
    ]
